- name: install maven
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - maven
  - mysql

- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: install packages
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: renaming jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app

- name: copying shipping service to default
  ansible.builtin.template:
    src: shipping.service.j2
    dest: /etc/systemd/system/shipping.service

- name: systemctl daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable shipping
  ansible.builtin.service:
    name: shipping
    state: started
    enabled: yes

- name: importing data
  community.mysql.mysql_db:
    login_user: root
    login_password: RoboShop@1
    login_host: mysql.liveyourlife.site
    state: import
    name: all
    target: "{{ item }}"
  loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql

- name: restart shipping
  ansible.builtin.service:
    name: shipping
    state: restarted
