- name: install mysql 
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: start and enable mysql
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: setup root password
  vars_files:
  - vault/mysql.yaml
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASSWORD }}