- name: app setup
  include_role:
    name: common
    tasks_from: app-setup.yaml

- name: nodejs setup
  include_role:
    name: common
    tasks_from: nodejs-setup.yaml


- name: copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present


- name: check whether data is loaded or not\
  ansible.builtin.command: mongosh --host mongodb.liveyourlife.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: print catalogue catalogue_output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: laoding products
  ansible.builtin.shell: mongo --host mongodb.liveyourlife.site < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0

  
- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd-setup.yaml



