- name: install python packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - python
  - gcc
  - python3-devel

- name: install dependencies
  ansible.builtin.npm:
    requirements: requirements.txt
    executable: pip3.9
  args:
    chdir: /app
